### ISSUE TITLE
bug - IOS 15. buttons (and other elements) are not pressed at the top (in the area of 50-60 pixels from the top)

### ISSUE THREAD

**Issue by bv-it** [lm/navigation-stack-backport#3]
bug - IOS 15. buttons (and other elements) are not pressed at the top (in the area of 50-60 pixels from the top)

**Comment by lm** [comment]
Hello, please provide full reproducible SwiftUI view code or project and specify exact iOS version where the problem occurs.

**Comment by bv-it** [comment]
Hello, any empty project. iphone 7 ios 15.0

**Comment by lm** [comment]
Sorry this is not much to go with. Feel free to reopen once you will have completely reproducible example code/project and steps guide. Screenshot/video may be also helpful.
