### ISSUE TITLE
bug - IOS 15. If there are many pages, an error occurs (or when we click too fast to open the page)

### ISSUE THREAD

**Issue by bv-it** [lm/navigation-stack-backport#5]
bug - IOS 15. If there are many pages, an error occurs (or when we click too fast to open the page)
- 10-20 pages
- 3-4 levels

func view(for item: NavigationPathItem, index: Int) -> AnyView {
        for destination in destinations.values {
            if let view = destination.view(item, index) {
                return view
            }
        }

        return AnyView(Text("Unload the application from memory and run it again"))
    }

**Comment by lm** [comment]
Sorry this is not much to go with. Feel free to reopen once you will have completely reproducible example code/project and steps guide. Screenshot/video may be also helpful.
